import { ACTION_TYPE } from "../../../helper/constants";

export const FETCH_AUTH_USER_FAILED = `FETCH_AUTH_USER${ACTION_TYPE.FAILED}`;
export const FETCH_AUTH_USER_LOADING = `FETCH_AUTH_USER${ACTION_TYPE.LOADING}`;
export const FETCH_AUTH_USER_SUCCESS = `FETCH_AUTH_USER${ACTION_TYPE.SUCCESS}`;
// export const FETCH_USER_PROFILE_INFOS_FAILED = `FETCH_USER_PROFILE_INFOS${ACTION_TYPE.FAILED}`;
// export const FETCH_USER_PROFILE_INFOS_LOADING = `FETCH_USER_PROFILE_INFOS${ACTION_TYPE.LOADING}`;
// export const FETCH_USER_PROFILE_INFOS_SUCCESS = `FETCH_USER_PROFILE_INFOS${ACTION_TYPE.SUCCESS}`;
// export const UPDATE_USER_PROFILE_INFOS_FAILED = `UPDATE_USER_PROFILE_INFOS${ACTION_TYPE.FAILED}`;
// export const UPDATE_USER_PROFILE_INFOS_LOADING = `UPDATE_USER_PROFILE_INFOS${ACTION_TYPE.LOADING}`;
// export const UPDATE_USER_PROFILE_INFOS_SUCCESS = `UPDATE_USER_PROFILE_INFOS${ACTION_TYPE.SUCCESS}`;
