import { ACTION_TYPE } from "../../../helper/constants";

export const FETCH_AUTH_USER_FAILED = `FETCH_AUTH_USER${ACTION_TYPE.FAILED}`;
export const FETCH_AUTH_USER_LOADING = `FETCH_AUTH_USER${ACTION_TYPE.LOADING}`;
export const FETCH_AUTH_USER_SUCCESS = `FETCH_AUTH_USER${ACTION_TYPE.SUCCESS}`;
export const FETCH_USER_PROFILE_INFOS_FAILED = `FETCH_USER_PROFILE_INFOS${ACTION_TYPE.FAILED}`;
export const FETCH_USER_PROFILE_INFOS_LOADING = `FETCH_USER_PROFILE_INFOS${ACTION_TYPE.LOADING}`;
export const FETCH_USER_PROFILE_INFOS_SUCCESS = `FETCH_USER_PROFILE_INFOS${ACTION_TYPE.SUCCESS}`;
export const UPDATE_USER_PROFILE_INFOS_FAILED = `UPDATE_USER_PROFILE_INFOS${ACTION_TYPE.FAILED}`;
export const UPDATE_USER_PROFILE_INFOS_LOADING = `UPDATE_USER_PROFILE_INFOS${ACTION_TYPE.LOADING}`;
export const UPDATE_USER_PROFILE_INFOS_SUCCESS = `UPDATE_USER_PROFILE_INFOS${ACTION_TYPE.SUCCESS}`;
export const FETCH_USER_PROFILE_PENDING = "FETCH_USER_PROFILE_PENDING";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_ERROR = "FETCH_USER_PROFILE_ERROR";

export const UPDATE_USER_PROFILE_PENDING = "UPDATE_USER_PROFILE_PENDING";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_ERROR = "UPDATE_USER_PROFILE_ERROR";

export const UPDATE_USER_PASSWORD_PENDING = "UPDATE_USER_PASSWORD_PENDING";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
export const UPDATE_USER_PASSWORD_ERROR = "UPDATE_USER_PASSWORD_ERROR";

export const FETCH_USER_PHYSICAL_METRICS_PENDING =
  "FETCH_USER_PHYSICAL_METRICS_PENDING";
export const FETCH_USER_PHYSICAL_METRICS_SUCCESS =
  "FETCH_USER_PHYSICAL_METRICS_SUCCESS";
export const FETCH_USER_PHYSICAL_METRICS_ERROR =
  "FETCH_USER_PHYSICAL_METRICS_ERROR";

export const ADD_USER_PHYSICAL_METRICS_PENDING =
  "ADD_USER_PHYSICAL_METRICS_PENDING";
export const ADD_USER_PHYSICAL_METRICS_SUCCESS =
  "ADD_USER_PHYSICAL_METRICS_SUCCESS";
export const ADD_USER_PHYSICAL_METRICS_ERROR =
  "ADD_USER_PHYSICAL_METRICS_ERROR";

export const RESET_PROFILE_UPDATE_VALUE = "RESET_PROFILE_UPDATE_VALUE";