export const FETCH_USER_PROFILE_INFOS_PENDING = 'FETCH_USER_PROFILE_INFOS_PENDING';
export const FETCH_USER_PROFILE_INFOS_SUCCESS = 'FETCH_USER_PROFILE_INFOS_SUCCESS';
export const FETCH_USER_PROFILE_INFOS_ERROR = 'FETCH_USER_PROFILE_INFOS_ERROR';

export const UPDATE_USER_PROFILE_INFOS_PENDING = "UPDATE_USER_PROFILE_INFOS_PENDING";
export const UPDATE_USER_PROFILE_INFOS_SUCCESS = "UPDATE_USER_PROFILE_INFOS_SUCCESS";
export const UPDATE_USER_PROFILE_INFOS_ERROR = "UPDATE_USER_PROFILE_INFOS_ERROR";

export const UPDATE_USER_PASSWORD_PENDING = "UPDATE_USER_PASSWORD_PENDING";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS"; 
export const UPDATE_USER_PASSWORD_ERROR = "UPDATE_USER_PASSWORD_ERROR";

export const FETCH_USER_BODY_INFOS_PENDING = 'FETCH_USER_BODY_INFOS_PENDING';
export const FETCH_USER_BODY_INFOS_SUCCESS = 'FETCH_USER_BODY_INFOS_SUCCESS';
export const FETCH_USER_BODY_INFOS_ERROR = 'FETCH_USER_BODY_INFOS_ERROR';

export const UPDATE_USER_BODY_INFOS_PENDING = "UPDATE_USER_BODY_INFOS_PENDING";
export const UPDATE_USER_BODY_INFOS_SUCCESS = "UPDATE_USER_BODY_INFOS_SUCCESS";
export const UPDATE_USER_BODY_INFOS_ERROR = "UPDATE_USER_BODY_INFOS_ERROR";