import { ACTION_TYPE } from "../../../helper/constants";

export const GET_CONVERSATIONS_FAILED = `GET_CONVERSATIONS${ACTION_TYPE.FAILED}`;
export const GET_CONVERSATIONS_LOADING = `GET_CONVERSATIONS${ACTION_TYPE.LOADING}`;
export const GET_CONVERSATIONS_SUCCESS = `GET_CONVERSATIONS${ACTION_TYPE.SUCCESS}`;
// export const CREATE_CONVERSATION_FAILED = `CREATE_CONVERSATION${ACTION_TYPE.FAILED}`;
// export const CREATE_CONVERSATION_LOADING = `CREATE_CONVERSATION${ACTION_TYPE.LOADING}`;
// export const CREATE_CONVERSATION_SUCCESS = `CREATE_CONVERSATION${ACTION_TYPE.SUCCESS}`;
