import { ACTION_TYPE } from "../../../helper/constants";

export const GET_CONVERSATION_MESSAGES_FAILED = `GET_CONVERSATION_MESSAGES${ACTION_TYPE.FAILED}`;
export const GET_CONVERSATION_MESSAGES_LOADING = `GET_CONVERSATION_MESSAGES${ACTION_TYPE.LOADING}`;
export const GET_CONVERSATION_MESSAGES_SUCCESS = `GET_CONVERSATION_MESSAGES${ACTION_TYPE.SUCCESS}`;
