import { ACTION_TYPE } from "../../../helper/constants";

export const GET_CONVERSATION_MESSAGES_FAILED = `GET_CONVERSATION_MESSAGES${ACTION_TYPE.FAILED}`;
export const GET_CONVERSATION_MESSAGES_LOADING = `GET_CONVERSATION_MESSAGES${ACTION_TYPE.LOADING}`;
export const GET_CONVERSATION_MESSAGES_SUCCESS = `GET_CONVERSATION_MESSAGES${ACTION_TYPE.SUCCESS}`;
export const POST_MESSAGE_FAILED = `POST_MESSAGE${ACTION_TYPE.FAILED}`;
export const POST_MESSAGE_LOADING = `POST_MESSAGE${ACTION_TYPE.LOADING}`;
export const POST_MESSAGE_SUCCESS = `POST_MESSAGE${ACTION_TYPE.SUCCESS}`;
