import { ACTION_TYPE } from "../../../helper/constants";

export const GET_PROGRAMS_FAILED = `GET_PROGRAMS${ACTION_TYPE.FAILED}`;
export const GET_PROGRAMS_LOADING = `GET_PROGRAMS${ACTION_TYPE.LOADING}`;
export const GET_PROGRAMS_SUCCESS = `GET_PROGRAMS${ACTION_TYPE.SUCCESS}`;
export const CREATE_PROGRAM_FAILED = `CREATE_PROGRAM${ACTION_TYPE.FAILED}`;
export const CREATE_PROGRAM_LOADING = `CREATE_PROGRAM${ACTION_TYPE.LOADING}`;
export const CREATE_PROGRAM_SUCCESS = `CREATE_PROGRAM${ACTION_TYPE.SUCCESS}`;
