export const GET_PROGRAMS_FAILED = `GET_PROGRAMS_FAILED`
export const GET_PROGRAMS_LOADING = `GET_PROGRAMS_LOADING`
export const GET_PROGRAMS_SUCCESS = `GET_PROGRAMS_SUCCESS`
export const CLEAN_GET_PROGRAMS = `CLEAN_GET_PROGRAMS`

export const GET_ONE_FAILED = `GET_ONE_FAILED`
export const GET_ONE_LOADING = `GET_ONE_LOADING`
export const GET_ONE_SUCCESS = `GET_ONE_SUCCESS`
export const CLEAN_GET_ONE = `CLEAN_GET_ONE`

export const CREATE_PROGRAM_FAILED = `CREATE_PROGRAM_FAILED`
export const CREATE_PROGRAM_LOADING = `CREATE_PROGRAM_LOADING`
export const CREATE_PROGRAM_SUCCESS = `CREATE_PROGRAM_SUCCESS`
export const CLEAN_CREATE_PROGRAM = `CLEAN_CREATE_PROGRAM`

export const UPDATE_PROGRAM_FAILED = `UPDATE_PROGRAM_FAILED`
export const UPDATE_PROGRAM_LOADING = `UPDATE_PROGRAM_LOADING`
export const UPDATE_PROGRAM_SUCCESS = `UPDATE_PROGRAM_SUCCESS`
export const CLEAN_UPDATE_PROGRAM = `CLEAN_UPDATE_PROGRAM`

export const DELETE_PROGRAM_FAILED = `DELETE_PROGRAM_FAILED`
export const DELETE_PROGRAM_LOADING = `DELETE_PROGRAM_LOADING`
export const DELETE_PROGRAM_SUCCESS = `DELETE_PROGRAM_SUCCESS`
export const CLEAN_DELETE_PROGRAM = `CLEAN_DELETE_PROGRAM`
