export const CREATE_COACH_PROFILE_FAILED = `CREATE_COACH_PROFILE_FAILED`
export const CREATE_COACH_PROFILE_LOADING = `CREATE_COACH_PROFILE_LOADING`
export const CREATE_COACH_PROFILE_SUCCESS = `CREATE_COACH_PROFILE_SUCCESS`

export const FETCH_COACH_PROFILE_FAILED = `FETCH_COACH_PROFILE_FAILED`
export const FETCH_COACH_PROFILE_LOADING = `FETCH_COACH_PROFILE_LOADING`
export const FETCH_COACH_PROFILE_SUCCESS = `FETCH_COACH_PROFILE_SUCCESS`

export const UPDATE_COACH_PROFILE_FAILED = `UPDATE_COACH_PROFILE_FAILED`
export const UPDATE_COACH_PROFILE_LOADING = `UPDATE_COACH_PROFILE_LOADING`
export const UPDATE_COACH_PROFILE_SUCCESS = `UPDATE_COACH_PROFILE_SUCCESS`
