import { ACTION_TYPE } from '../../../helper/constants'

export const GET_CUSTOMERS_FAILED = `GET_CUSTOMERS${ACTION_TYPE.FAILED}`
export const GET_CUSTOMERS_LOADING = `GET_CUSTOMERS${ACTION_TYPE.LOADING}`
export const GET_CUSTOMERS_SUCCESS = `GET_CUSTOMERS${ACTION_TYPE.SUCCESS}`

export const FETCH_CUSTOMER_FAILED = `FETCH_CUSTOMER_FAILED`
export const FETCH_CUSTOMER_LOADING = `FETCH_CUSTOMER_LOADING`
export const FETCH_CUSTOMER_SUCCESS = `FETCH_CUSTOMER_SUCCESS`
export const CLEAN_FETCH_CUSTOMER = `CLEAN_FETCH_CUSTOMER`

export const CREATE_FAILED = `CREATE${ACTION_TYPE.FAILED}`
export const CREATE_LOADING = `CREATE${ACTION_TYPE.LOADING}`
export const CREATE_SUCCESS = `CREATE${ACTION_TYPE.SUCCESS}`
