import { ACTION_TYPE } from "../../../helper/constants";

export const AUTO_LOGIN_FAILED = `AUTO_LOGIN${ACTION_TYPE.FAILED}`;
export const AUTO_LOGIN_LOADING = `AUTO_LOGIN${ACTION_TYPE.LOADING}`;
export const AUTO_LOGIN_SUCCESS = `AUTO_LOGIN${ACTION_TYPE.SUCCESS}`;
export const LOGIN_FAILED = `LOGIN${ACTION_TYPE.FAILED}`;
export const LOGIN_LOADING = `LOGIN${ACTION_TYPE.LOADING}`;
export const LOGIN_SUCCESS = `LOGIN${ACTION_TYPE.SUCCESS}`;
export const LOGOUT = `LOGOUT`;
