import { ACTION_TYPE } from "../../../helper/constants";

export const LOGIN_FAILED = `LOGIN${ACTION_TYPE.FAILED}`;
export const LOGIN_LOADING = `LOGIN${ACTION_TYPE.LOADING}`;
export const LOGIN_SUCCESS = `LOGIN${ACTION_TYPE.SUCCESS}`;
export const LOGOUT = `LOGOUT`;
export const REGISTER_FAILED = `REGISTER${ACTION_TYPE.FAILED}`;
export const REGISTER_LOADING = `REGISTER${ACTION_TYPE.LOADING}`;
export const REGISTER_SUCCESS = `REGISTER${ACTION_TYPE.SUCCESS}`;
