export const GET_EXERCISES_FAILED = `GET_EXERCISES_FAILED`
export const GET_EXERCISES_LOADING = `GET_EXERCISES_LOADING`
export const GET_EXERCISES_SUCCESS = `GET_EXERCISES_SUCCESS`
export const CLEAN_GET_EXERCISES = `CLEAN_GET_EXERCISES`

export const CREATE_EXERCISE_FAILED = `CREATE_EXERCISE_FAILED`
export const CREATE_EXERCISE_LOADING = `CREATE_EXERCISE_LOADING`
export const CREATE_EXERCISE_SUCCESS = `CREATE_EXERCISE_SUCCESS`
export const CLEAN_CREATE_EXERCISE = `CLEAN_CREATE_EXERCISE`

export const UPDATE_EXERCISE_FAILED = `UPDATE_EXERCISE_FAILED`
export const UPDATE_EXERCISE_LOADING = `UPDATE_EXERCISE_LOADING`
export const UPDATE_EXERCISE_SUCCESS = `UPDATE_EXERCISE_SUCCESS`
export const CLEAN_UPDATE_EXERCISE = `CLEAN_UPDATE_EXERCISE`

export const DELETE_EXERCISE_FAILED = `DELETE_EXERCISE_FAILED`
export const DELETE_EXERCISE_LOADING = `DELETE_EXERCISE_LOADING`
export const DELETE_EXERCISE_SUCCESS = `DELETE_EXERCISE_SUCCESS`
export const CLEAN_DELETE_EXERCISE = `CLEAN_DELETE_EXERCISE`
