import { ACTION_TYPE } from "../../../helper/constants";

export const GET_EXERCISES_FAILED = `GET_EXERCISES${ACTION_TYPE.FAILED}`;
export const GET_EXERCISES_LOADING = `GET_EXERCISES${ACTION_TYPE.LOADING}`;
export const GET_EXERCISES_SUCCESS = `GET_EXERCISES${ACTION_TYPE.SUCCESS}`;
export const CREATE_EXERCISE_FAILED = `CREATE_EXERCISE${ACTION_TYPE.FAILED}`;
export const CREATE_EXERCISE_LOADING = `CREATE_EXERCISE${ACTION_TYPE.LOADING}`;
export const CREATE_EXERCISE_SUCCESS = `CREATE_EXERCISE${ACTION_TYPE.SUCCESS}`;
