import { ACTION_TYPE } from "../../../helper/constants";

export const GET_SERVICES_FAILED = `GET_SERVICES${ACTION_TYPE.FAILED}`;
export const GET_SERVICES_LOADING = `GET_SERVICES${ACTION_TYPE.LOADING}`;
export const GET_SERVICES_SUCCESS = `GET_SERVICES${ACTION_TYPE.SUCCESS}`;
export const CREATE_FAILED = `CREATE${ACTION_TYPE.FAILED}`;
export const CREATE_LOADING = `CREATE${ACTION_TYPE.LOADING}`;
export const CREATE_SUCCESS = `CREATE${ACTION_TYPE.SUCCESS}`;
