import { ACTION_TYPE } from "../../../helper/constants";

export const GET_ALL_FAILED = `GET_ALL${ACTION_TYPE.FAILED}`;
export const GET_ALL_LOADING = `GET_ALL${ACTION_TYPE.LOADING}`;
export const GET_ALL_SUCCESS = `GET_ALL${ACTION_TYPE.SUCCESS}`;
export const CREATE_FAILED = `CREATE${ACTION_TYPE.FAILED}`;
export const CREATE_LOADING = `CREATE${ACTION_TYPE.LOADING}`;
export const CREATE_SUCCESS = `CREATE${ACTION_TYPE.SUCCESS}`;
