import { ACTION_TYPE } from "../../../helper/constants";

export const GET_WORKOUTS_FAILED = `GET_WORKOUTS${ACTION_TYPE.FAILED}`;
export const GET_WORKOUTS_LOADING = `GET_WORKOUTS${ACTION_TYPE.LOADING}`;
export const GET_WORKOUTS_SUCCESS = `GET_WORKOUTS${ACTION_TYPE.SUCCESS}`;
export const CREATE_WORKOUT_FAILED = `CREATE_WORKOUT${ACTION_TYPE.FAILED}`;
export const CREATE_WORKOUT_LOADING = `CREATE_WORKOUT${ACTION_TYPE.LOADING}`;
export const CREATE_WORKOUT_SUCCESS = `CREATE_WORKOUT${ACTION_TYPE.SUCCESS}`;
