export const GET_WORKOUTS_FAILED = `GET_WORKOUTS_FAILED`
export const GET_WORKOUTS_LOADING = `GET_WORKOUTS_LOADING`
export const GET_WORKOUTS_SUCCESS = `GET_WORKOUTS_SUCCESS`
export const CLEAN_GET_WORKOUTS = `CLEAN_GET_WORKOUTS`

export const FETCH_WORKOUT_FAILED = `FETCH_WORKOUT_FAILED`
export const FETCH_WORKOUT_LOADING = `FETCH_WORKOUT_LOADING`
export const FETCH_WORKOUT_SUCCESS = `FETCH_WORKOUT_SUCCESS`
export const CLEAN_FETCH_WORKOUT = `CLEAN_FETCH_WORKOUT`

export const CREATE_WORKOUT_FAILED = `CREATE_WORKOUT_FAILED`
export const CREATE_WORKOUT_LOADING = `CREATE_WORKOUT_LOADING`
export const CREATE_WORKOUT_SUCCESS = `CREATE_WORKOUT_SUCCESS`
export const CLEAN_CREATE_WORKOUT = `CLEAN_CREATE_WORKOUT`

export const UPDATE_WORKOUT_FAILED = `UPDATE_WORKOUT_FAILED`
export const UPDATE_WORKOUT_LOADING = `UPDATE_WORKOUT_LOADING`
export const UPDATE_WORKOUT_SUCCESS = `UPDATE_WORKOUT_SUCCESS`
export const CLEAN_UPDATE_WORKOUT = `CLEAN_UPDATE_WORKOUT`

export const DELETE_WORKOUT_FAILED = `DELETE_WORKOUT_FAILED`
export const DELETE_WORKOUT_LOADING = `DELETE_WORKOUT_LOADING`
export const DELETE_WORKOUT_SUCCESS = `DELETE_WORKOUT_SUCCESS`
export const CLEAN_DELETE_WORKOUT = `CLEAN_DELETE_WORKOUT`
