name: Node CI

on:
  push:
    branches: [staging, master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        run: npm ci

      - name: Run prettier
        run: npm run prettier

      - name: Extract branch name
        id: branch_name
        run: echo ::set-output name=BRANCH_NAME::${GITHUB_REF##*/}

      - name: Build app
        if: steps.branch_name.outputs.BRANCH_NAME == 'master'
        run: npm run build
        with:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          REACT_APP_GOOGLE_CLIENT_SECRET: ${{ secrets.REACT_APP_GOOGLE_CLIENT_SECRET }}

      - name: Deploy 🚀
        if: steps.branch_name.outputs.BRANCH_NAME == 'master'
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
