import AlertUI from "./alert/Alert";
import AvatarUI from "./avatar/Avatar";
import ButtonUI from "./button/Button";
import CheckboxUI from "./form/checkbox/Checkbox";
import DayPickerUI from "./form/date-picker/DayPicker";
import DialogUI from "./modal/Dialog";
import EditorInputUI from "./form/editor-input/EditorInput";
import FieldUI from "./form/field/Field";
import FlexUI from "./layout/Flex";
import FormUI from "./form/Form";
import ImageUI from "./image/Image";
import InputUI from "./form/input/Input";
import LabelUI from "./form/label/Label";
import PaneUI from "./pane/Pane";
import RadioButtonUI from "./form/radio-button/RadioButton";
import SelectUI from "./form/select/Select";
import SideModalUI from "./modal/SideModal";
import SpinnerUI from "./loader/Spinner";
import SwitchUI from "./switch/Switch";
import TabListUI from "./tab/TabList";
import TabUI from "./tab/Tab";
import TextUI from "./typography/Text";
import TitleUI from "./typography/Title";
import toasterUI from "./toaster/toaster";
import AutocompleteUI from "./autocomplete/autocomplete";
import TagUI from "./tag/tag"
import TextInputUI from "./text-input/TextInput"

export const Alert = AlertUI;
export const Avatar = AvatarUI;
export const Button = ButtonUI;
export const Checkbox = CheckboxUI;
export const Dialog = DialogUI;
export const DayPicker = DayPickerUI;
export const EditorInput = EditorInputUI;
export const Field = FieldUI;
export const Flex = FlexUI;
export const Form = FormUI;
export const Image = ImageUI;
export const Input = InputUI;
export const Label = LabelUI;
export const Pane = PaneUI;
export const RadioButton = RadioButtonUI;
export const Select = SelectUI;
export const SideModal = SideModalUI;
export const Spinner = SpinnerUI;
export const Switch = SwitchUI;
export const Tab = TabUI;
export const TabList = TabListUI;
export const Text = TextUI;
export const Title = TitleUI;
export const toaster = toasterUI;
export const Autocomplete = AutocompleteUI;
export const Tag = TagUI;
export const TextInput = TextInputUI;