import AlertUI from "./alert/Alert";
import ButtonUI from "./button/Button";
import FieldUI from "./form/field/Field";
import FormUI from "./form/Form";
import InputUI from "./form/input/Input";
import PaneUI from "./pane/Pane";
import SideModalUI from "./modal/SideModal";
import SpinnerUI from "./loader/Spinner";
import TextUI from "./text/Text";
import TitleUI from "./typography/Title";
import toasterUI from "./toaster/toaster";
import LabelUI from "./form/label/Label";
import FlexUI from "./layout/Flex";
import EditorInputUI from "./form/editor-input/EditorInput";
import ImageUI from "./image/Image";
import SwitchUI from "./switch/Switch";

export const Alert = AlertUI;
export const Button = ButtonUI;
export const Field = FieldUI;
export const Form = FormUI;
export const Input = InputUI;
export const Label = LabelUI;
export const Pane = PaneUI;
export const SideModal = SideModalUI;
export const Spinner = SpinnerUI;
export const Text = TextUI;
export const Title = TitleUI;
export const toaster = toasterUI;
export const Flex = FlexUI;
export const EditorInput = EditorInputUI;
export const Image = ImageUI;
export const Switch = SwitchUI;
