export const GET_ASSIGNMENTS_FAILED = `GET_ASSIGNMENTS_FAILED`;
export const GET_ASSIGNMENTS_LOADING = `GET_ASSIGNMENTS_LOADING`;
export const GET_ASSIGNMENTS_SUCCESS = `GET_ASSIGNMENTS_SUCCESS`;
export const CLEAN_GET_ASSIGNMENTS = `CLEAN_GET_ASSIGNMENTS`;

export const CREATE_ASSIGNMENT_FAILED = `CREATE_ASSIGNMENT_FAILED`;
export const CREATE_ASSIGNMENT_LOADING = `CREATE_ASSIGNMENT_LOADING`;
export const CREATE_ASSIGNMENT_SUCCESS = `CREATE_ASSIGNMENT_SUCCESS`;
export const CLEAN_CREATE_ASSIGNMENT = `CLEAN_CREATE_ASSIGNMENT`;

export const UPDATE_ASSIGNMENT_FAILED = `UPDATE_ASSIGNMENT_FAILED`;
export const UPDATE_ASSIGNMENT_LOADING = `UPDATE_ASSIGNMENT_LOADING`;
export const UPDATE_ASSIGNMENT_SUCCESS = `UPDATE_ASSIGNMENT_SUCCESS`;
export const CLEAN_UPDATE_ASSIGNMENT = `CLEAN_UPDATE_ASSIGNMENT`;

export const DELETE_ASSIGNMENT_FAILED = `DELETE_ASSIGNMENT_FAILED`;
export const DELETE_ASSIGNMENT_LOADING = `DELETE_ASSIGNMENT_LOADING`;
export const DELETE_ASSIGNMENT_SUCCESS = `DELETE_ASSIGNMENT_SUCCESS`;
export const CLEAN_DELETE_ASSIGNMENT = `CLEAN_DELETE_ASSIGNMENT`;
